name: "sensevoice-small"
backend: "python"
max_batch_size: 0

input [
  {
    name: "funasr_audio"
    data_type: TYPE_STRING
    dims: [-1]
  },
  {
    name: "language"
    data_type: TYPE_INT32
    dims: [1]
  },
  {
    name: "textnorm"
    data_type: TYPE_INT32
    dims: [1]
  }
]

output [
  {
    name: "logits"
    data_type: TYPE_FP32
    dims: [-1, -1, -1]
  },
  {
    name: "encoder_out_lens"
    data_type: TYPE_INT32
    dims: [-1]
  }
]


parameters: {
  key: "backend_type"
  value: { string_value: "ascend_om" }
}

parameters: {
  key: "modal_type_list"
  value: { string_value: "[\"funasr_audio\"]" }
}

parameters: {
  key: "backend_config"
  value: { string_value: "{\"device_id\": 0}" }
}

parameters: {
  key: "infer_config"
  value: { string_value: "{\"infer_mode\": \"dymshape\"}" }
}

parameters: {
  key: "processor_config"
  value: {
    string_value: "{\"cmvn_file\": \"/data/models/MindSDK/SenseVoiceSmall/am.mvn\", \"fs\": 16000, \"window\": \"hamming\", \"frame_shift\": 10, \"frame_length\": 25, \"n_mels\": 560, \"use_dither\": false, \"sample_rate\": 16000}"
  }
}