apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.appName }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: {{ .Values.frontend.appName }}
      port: 8080
      targetPort: 8080
      nodePort: {{ .Values.frontend.service.port }}
      protocol: TCP
  selector:
    app: {{ .Values.frontend.appName }}